### PR TITLE
Fixing not defined error and adjusting headers to http standards

### PR DESCRIPTION
**Pull request by Clemens-E**
Nginx always deleted the user_id header while passing it.
Seems that Apache and Nginx drop headers with underscores.
<https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/?highlight=disappearing%20http%20headers#missing-disappearing-http-headers>

### CODE REVIEW

**Comment by takase1121** [comment]
According to the link you attached, headers with underscorce are valid too.

**Comment by Deivu** [comment]
Thanks for bringing this PR, and I think I didn't take account for this kind of issue on queries in get endpoints. 

In my opinion, what if we just put the ID in a query string, and just put auth in headers. I believe this would ensure compatibility in most systems

**Comment by takase1121** [comment]
I agree with that.

**Comment by Clemens-E** [comment]
Yeah that's my bad, they are valid, but both nginx and Apache will drop the headers. Anyway, I agree with the querrys version, I already wondered why you would do it over headers.

**Comment by Deivu** [comment]
That settles it, I'll update the library to fix those issue probably this night to tomorrow afternoon. 
You will receive an update on my Server once the update is live

**Pull request closed without merging**
