### PR TITLE
Add ability to run Haruna through Docker

### PR DESCRIPTION
**Pull request by Lymdun**
- Add dockerfile and instructions to run Haruna through a docker container.
- Add docker-compose example
- Add github action to build & publish haruna image
- Load config from varenv if no config file provided

### CODE REVIEW

**Comment by Lymdun** [comment]
Hey @Deivu!
Would you be interested if I write a github action (in this PR) in order to automatically publish docker images to docker hub? (it would requires a docker hub account)

**Comment by 0t4u** [comment]
Hey @Lymdun,
Thank you for the contribution!
@Deivu has asked me to review this PR.
It would be better if we pushed the docker images to the GitHub Container Registry, if possible.

**Comment by Lymdun** [comment]
Heya @0t4u,
Thanks for your answer! Of course this is possible, I've pushed a commit for it. As I did it, the github action will be triggered after each release, if that's fine with you.

**Comment by Lymdun** [comment]
Note: this may requires refactoring **HarunaConfig** in order to be able to pass parameters as env variables, which would be way more simple than passing the config file to a docker compose, for example.

**Comment by Lymdun** [comment]
Poke @Deivu @0t4u

**Pull request merged**
